### ISSUE TITLE
Responses Curl

### ISSUE THREAD

**Issue by mlahlouh** [mabumusa1/kub8-api#3]
Sample Success request:
```
ubuntu@ip-172-31-28-109:~$ curl http://localhost:8001/apis/apps/v1/namespaces/default/statefulsets -k -H "Content-Type: application/yaml" -XPOST -d '
> apiVersion: apps/v1
> kind: StatefulSet
> metadata:
>   name: tadamon
> spec:
>   selector:
>     matchLabels:
>       app: tadamon-mautic # has to match .spec.template.metadata.labels
>   serviceName: "tadamon-service"
>   replicas: 1 # by default is 1
>   template:
>     metadata:
>       labels:
>         app: tadamon-mautic # has to match .spec.selector.matchLabels
>     spec:
>       terminationGracePeriodSeconds: 10
        - name: MAUTIC_DB_NAME
          value: "tadamon"
        - name: MAUTIC_DB_HOST
          value: "db.internal"
        - name: client-name
          value: "tadamon"
        ports:
        - containerPort: 80
          name: tadamon
        volumeMounts:
        - name: tadamon-claim
          mountPath: /code
        tty: true
        workingDir: /code
      restartPolicy: Always
  volumeClaimTemplates:
>       containers:
>       - name: tadamon-container
>         image: nginx
>         env:
>         - name: MAUTIC_DB_USER
>           value: "tadamon_user"
>         - name: MAUTIC_DB_PASSWORD
>           value: "QAZ2wsx3edc4rfv"
>         - name: MAUTIC_DB_NAME
>           value: "tadamon"
>         - name: MAUTIC_DB_HOST
>           value: "db.internal"
>         - name: client-name
>           value: "tadamon"
>         ports:
>         - containerPort: 80
>           name: tadamon
>         volumeMounts:
>         - name: tadamon-claim
>           mountPath: /code
>         tty: true
>         workingDir: /code
>       restartPolicy: Always
>   volumeClaimTemplates:
>   - metadata:
>       name: tadamon-claim
>     spec:
>       accessModes: [ "ReadWriteOnce" ]
>       storageClassName: "gp2"
>       resources:
>         requests:
>           storage: 10Gi  '
{
  "kind": "StatefulSet",
  "apiVersion": "apps/v1",
  "metadata": {
    "name": "tadamon",
    "namespace": "default",
    "uid": "48e29310-999b-41d4-b4e9-6b8cd3a13098",
    "resourceVersion": "2367870",
    "generation": 1,
    "creationTimestamp": "2022-03-27T12:01:08Z",
    "managedFields": [
      {
        "manager": "curl",
        "operation": "Update",
        "apiVersion": "apps/v1",
        "time": "2022-03-27T12:01:08Z",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:spec": {
            "f:podManagementPolicy": {},
            "f:replicas": {},
            "f:revisionHistoryLimit": {},
            "f:selector": {},
            "f:serviceName": {},
            "f:template": {
              "f:metadata": {
                "f:labels": {
                  ".": {},
                  "f:app": {}
                }
              },
              "f:spec": {
                "f:containers": {
                  "k:{\"name\":\"tadamon-container\"}": {
                    ".": {},
                    "f:env": {
                      ".": {},
                      "k:{\"name\":\"MAUTIC_DB_HOST\"}": {
                        ".": {},
                        "f:name": {},
                        "f:value": {}
                      },
                      "k:{\"name\":\"MAUTIC_DB_NAME\"}": {
                        ".": {},
                        "f:name": {},
                        "f:value": {}
                      },
                      "k:{\"name\":\"MAUTIC_DB_PASSWORD\"}": {
                        ".": {},
                        "f:name": {},
                        "f:value": {}
                      },
                      "k:{\"name\":\"MAUTIC_DB_USER\"}": {
                        ".": {},
                        "f:name": {},
                        "f:value": {}
                      },
                      "k:{\"name\":\"client-name\"}": {
                        ".": {},
                        "f:name": {},
                        "f:value": {}
                      }
                    },
                    "f:image": {},
                    "f:imagePullPolicy": {},
                    "f:name": {},
                    "f:ports": {
                      ".": {},
                      "k:{\"containerPort\":80,\"protocol\":\"TCP\"}": {
                        ".": {},
                        "f:containerPort": {},
                        "f:name": {},
                        "f:protocol": {}
                      }
                    },
                    "f:resources": {},
                    "f:terminationMessagePath": {},
                    "f:terminationMessagePolicy": {},
                    "f:tty": {},
                    "f:volumeMounts": {
                      ".": {},
                      "k:{\"mountPath\":\"/code\"}": {
                        ".": {},
                        "f:mountPath": {},
                        "f:name": {}
                      }
                    },
                    "f:workingDir": {}
                  }
                },
                "f:dnsPolicy": {},
                "f:restartPolicy": {},
                "f:schedulerName": {},
                "f:securityContext": {},
                "f:terminationGracePeriodSeconds": {}
              }
            },
            "f:updateStrategy": {
              "f:rollingUpdate": {
                ".": {},
                "f:partition": {}
              },
              "f:type": {}
            },
            "f:volumeClaimTemplates": {}
          }
        }
      }
    ]
  },
  "spec": {
    "replicas": 1,
    "selector": {
      "matchLabels": {
        "app": "tadamon-mautic"
      }
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "app": "tadamon-mautic"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "tadamon-container",
            "image": "nginx",
            "workingDir": "/code",
            "ports": [
              {
                "name": "tadamon",
                "containerPort": 80,
                "protocol": "TCP"
              }
            ],
            "env": [
              {
                "name": "MAUTIC_DB_USER",
                "value": "tadamon_user"
              },
              {
                "name": "MAUTIC_DB_PASSWORD",
                "value": "QAZ2wsx3edc4rfv"
              },
              {
                "name": "MAUTIC_DB_NAME",
                "value": "tadamon"
              },
              {
                "name": "MAUTIC_DB_HOST",
                "value": "db.internal"
              },
              {
                "name": "client-name",
                "value": "tadamon"
              }
            ],
            "resources": {},
            "volumeMounts": [
              {
                "name": "tadamon-claim",
                "mountPath": "/code"
              }
            ],
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "Always",
            "tty": true
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 10,
        "dnsPolicy": "ClusterFirst",
        "securityContext": {},
        "schedulerName": "default-scheduler"
      }
    },
    "volumeClaimTemplates": [
      {
        "kind": "PersistentVolumeClaim",
        "apiVersion": "v1",
        "metadata": {
          "name": "tadamon-claim",
          "creationTimestamp": null
        },
        "spec": {
          "accessModes": [
            "ReadWriteOnce"
          ],
          "resources": {
            "requests": {
              "storage": "10Gi"
            }
          },
          "storageClassName": "gp2",
          "volumeMode": "Filesystem"
        },
        "status": {
          "phase": "Pending"
        }
      }
    ],
    "serviceName": "tadamon-service",
    "podManagementPolicy": "OrderedReady",
    "updateStrategy": {
      "type": "RollingUpdate",
      "rollingUpdate": {
        "partition": 0
      }
    },
    "revisionHistoryLimit": 10
  },
  "status": {
    "replicas": 0,
    "availableReplicas": 0
  }
}ubuntu@ip-172-31-28-109:~$

```

Sample error "AlreadyExists"
```
ubuntu@ip-172-31-28-109:~$ curl http://localhost:8001/apis/apps/v1/namespaces/default/statefulsets -k -H "Content-Type: application/yaml" -XPOST -d '
> apiVersion: apps/v1
> kind: StatefulSet
> metadata:
>   name: tadamon
> spec:
>   selector:
        - name: MAUTIC_DB_HOST
          value: "db.internal"
        - name: client-name
          value: "tadamon"
        ports:
        - containerPort: 80
          name: tadamon
        volumeMounts:
>     matchLabels:
>       app: tadamon-mautic # has to match .spec.template.metadata.labels
>   serviceName: "tadamon-service"
>   replicas: 1 # by default is 1
>   template:
>     metadata:
>       labels:
>         app: tadamon-mautic # has to match .spec.selector.matchLabels
>     spec:
>       terminationGracePeriodSeconds: 10
>       containers:
>       - name: tadamon-container
>         image: nginx
>         env:
>         - name: MAUTIC_DB_USER
>           value: "tadamon_user"
>         - name: MAUTIC_DB_PASSWORD
>           value: "QAZ2wsx3edc4rfv"
>         - name: MAUTIC_DB_NAME
>           value: "tadamon"
>         - name: MAUTIC_DB_HOST
>           value: "db.internal"
>         - name: client-name
>           value: "tadamon"
>         ports:
>         - containerPort: 80
>           name: tadamon
>         volumeMounts:
>         - name: tadamon-claim
>           mountPath: /code
>         tty: true
>         workingDir: /code
>       restartPolicy: Always
>   volumeClaimTemplates:
>   - metadata:
>       name: tadamon-claim
>     spec:
>       accessModes: [ "ReadWriteOnce" ]
>       storageClassName: "gp2"
>       resources:
>         requests:
>           storage: 10Gi  '
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "statefulsets.apps \"tadamon\" already exists",
  "reason": "AlreadyExists",
  "details": {
    "name": "tadamon",
    "group": "apps",
    "kind": "statefulsets"
  },
  "code": 409
}ubuntu@ip-172-31-28-109:~$
```

**Comment by mabumusa1** [comment]
In order to create a new install you need to follow these steps: 

1. https://kubernetes-client.github.io/javascript/classes/appsv1api.appsv1api-1.html#createnamespacedstatefulset
2. https://kubernetes-client.github.io/javascript/classes/corev1api.corev1api-1.html#createnamespacedservice

**Comment by mlahlouh** [comment]
```
demo.steercampaign.com  $request.domain
demo

$local.db_password


407780391754.dkr.ecr.ap-south-1.amazonaws.com/mautic_sc:latest


$local.aws_account_no .dkr.ecr. $request.region .amazonaws.com/ $local_repo_name :latest



a91db86aaa6a947ae8cf9a0ee09c740a-1073567115.ap-south-1.elb.amazonaws.com

$local.loadbalancer_uri


CREATE USER 'demo_user'@'%' IDENTIFIED WITH 'mysql_native_password' by 'QAZ2wsx3edc4rfv';
create database demo;
grant all on demo.* to 'demo_user'@'%';







apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: $request.id
spec:
  selector:
    matchLabels:
      app: $request.id 
  serviceName: $request.id
  replicas: 1 
  template:
    metadata:
      labels:
        app: $request.id 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: $request.id
        image: $local.aws_account_no .dkr.ecr. $request.region .amazonaws.com/ $local_repo_name :latest
        env:
        - name: MAUTIC_DB_USER
          value: $local.db_user
        - name: MAUTIC_DB_PASSWORD
          value: $local.db_pass
        - name: MAUTIC_DB_NAME
          value: $local.db_name
        - name: MAUTIC_DB_HOST
          value: db.internal
        - name: client-name
          value: $request.id        
        ports:
        - containerPort: 80
          name: $request.id
        volumeMounts:
        - name: $request.id
          mountPath: /code      
        tty: true
        workingDir: /code
      restartPolicy: Always          
  volumeClaimTemplates:
  - metadata:
      name: $request.id
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp2"
      resources:
        requests:
          storage: 10Gi  



apiVersion: v1
kind: Service
metadata:
  name: $request.id
  namespace: default
  labels:
    app: $request.id
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: $request.id
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack


apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: $request.id
  namespace: default
spec:
  dnsNames:
    - $request.domain
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod-ingress
  secretName: $request.id

	
	
	

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $request.id
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-ingress
status:
  loadBalancer:
    ingress:
      - hostname: >-
          $local.loadbalancer_uri
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - $request.domain
      secretName: $request.id
  rules:
    - host: $request.domain
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: $request.id
                port:
                  number: 80
```
